/* Generated By:JavaCC: Do not edit this line. NonXmlSyntaxConstants.java */
package com.thaiopensource.relaxng.nonxml;

public interface NonXmlSyntaxConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 40;
  int BASE_CHAR = 41;
  int IDEOGRAPHIC = 42;
  int LETTER = 43;
  int COMBINING_CHAR = 44;
  int DIGIT = 45;
  int EXTENDER = 46;
  int NMSTART = 47;
  int NMCHAR = 48;
  int NCNAME = 49;
  int HIGH_SURROGATE = 50;
  int LOW_SURROGATE = 51;
  int SURROGATE_PAIR = 52;
  int CHAR = 53;
  int CHAR_NOT_QUOT = 54;
  int CHAR_NOT_APOS = 55;
  int IDENTIFIER = 56;
  int ESCAPED_IDENTIFIER = 57;
  int PREFIX_STAR = 58;
  int PREFIXED_NAME = 59;
  int LITERAL = 60;
  int BYTE_ORDER_MARK = 61;
  int QNAME = 62;
  int S = 63;
  int ATT_START = 65;
  int ILLEGAL_MARKUP_CHAR = 70;
  int ILLEGAL_CONTENT_SEQUENCE = 78;
  int ILLEGAL_COMMENT_SEQUENCE = 80;
  int EMPTY_ELEMENT = 82;
  int START_TAG = 83;
  int END_TAG = 84;
  int ILLEGAL_CHAR = 85;

  int DEFAULT = 0;
  int CONTENT = 1;
  int STAG = 2;
  int LIT = 3;
  int LITA = 4;
  int COMMENT = 5;

  String[] tokenImage = {
    "<EOF>",
    "\"namespace\"",
    "\"default\"",
    "\"=\"",
    "\"inherit\"",
    "\"datatypes\"",
    "\"empty\"",
    "\"text\"",
    "\"notAllowed\"",
    "\"|\"",
    "\"&\"",
    "\",\"",
    "\"+\"",
    "\"?\"",
    "\"*\"",
    "\"element\"",
    "\"{\"",
    "\"}\"",
    "\"attribute\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"list\"",
    "\"mixed\"",
    "\"grammar\"",
    "\"start\"",
    "\"|=\"",
    "\"&=\"",
    "\"include\"",
    "\"externalRef\"",
    "\"parent\"",
    "\"string\"",
    "\"token\"",
    "\"[\"",
    "\"]\"",
    "\">>\"",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\t\"",
    "<SINGLE_LINE_COMMENT>",
    "<BASE_CHAR>",
    "<IDEOGRAPHIC>",
    "<LETTER>",
    "<COMBINING_CHAR>",
    "<DIGIT>",
    "<EXTENDER>",
    "<NMSTART>",
    "<NMCHAR>",
    "<NCNAME>",
    "<HIGH_SURROGATE>",
    "<LOW_SURROGATE>",
    "<SURROGATE_PAIR>",
    "<CHAR>",
    "<CHAR_NOT_QUOT>",
    "<CHAR_NOT_APOS>",
    "<IDENTIFIER>",
    "<ESCAPED_IDENTIFIER>",
    "<PREFIX_STAR>",
    "<PREFIXED_NAME>",
    "<LITERAL>",
    "\"\\ufeff\"",
    "<QNAME>",
    "<S>",
    "<token of kind 64>",
    "<ATT_START>",
    "<token of kind 66>",
    "<token of kind 67>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<ILLEGAL_MARKUP_CHAR>",
    "<token of kind 71>",
    "<token of kind 72>",
    "<token of kind 73>",
    "<token of kind 74>",
    "\"<!--\"",
    "<token of kind 76>",
    "<token of kind 77>",
    "\"]]>\"",
    "\"-->\"",
    "\"--\"",
    "<token of kind 81>",
    "<EMPTY_ELEMENT>",
    "<START_TAG>",
    "<END_TAG>",
    "<ILLEGAL_CHAR>",
  };

}
